services:
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=my-project-id
    ports:
      - "8085:8085"
    environment:
      - PUBSUB_PROJECT_ID=my-project-id